<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJqxEdDQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJqxEdDQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJqxEdDQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJqxEdDQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJqxEdDQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JqxEdDQ',
    'container.build_id' => '2d8db2cd',
    'container.build_time' => 1599169462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJqxEdDQ');
