<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVg6em3m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVg6em3m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVg6em3m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVg6em3m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVg6em3m\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vg6em3m',
    'container.build_id' => '080b6ca1',
    'container.build_time' => 1599165562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVg6em3m');
